[package]
name = "vcdiff-common"
repository = "https://github.com/ThinkingJoules/vcdiff-utils"
description = "Common structs, functions, and traits for vcdiff format"
license = "MIT"
version = "1.0.0"
edition = "2021"

