[package]
name = "vcdiff-merger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vcdiff-common ={ path = "../vcdiff-common"}
vcdiff-reader ={ path = "../vcdiff-reader"}
vcdiff-writer ={ path = "../vcdiff-writer"}

[dev-dependencies]
vcdiff-decoder ={ path = "../vcdiff-decoder"}